// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestaurantAPI.Models;

#nullable disable

namespace RestaurantAPI.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20260317150853_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestaurantAPI.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerName = "Muhammed",
                            Phone = "1231521"
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerName = "Çınar",
                            Phone = "0555555"
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitOnCost")
                        .HasColumnType("numeric");

                    b.Property<int>("UnitOnStock")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Price = 14m,
                            ProductName = "elma",
                            UnitOnCost = 8m,
                            UnitOnStock = 30
                        },
                        new
                        {
                            ProductId = 2,
                            Price = 15m,
                            ProductName = "elma",
                            UnitOnCost = 6m,
                            UnitOnStock = 5
                        },
                        new
                        {
                            ProductId = 3,
                            Price = 20m,
                            ProductName = "elma",
                            UnitOnCost = 10m,
                            UnitOnStock = 20
                        },
                        new
                        {
                            ProductId = 4,
                            Price = 30m,
                            ProductName = "elma",
                            UnitOnCost = 15m,
                            UnitOnStock = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
